# Project Name
spring.application.name=laser-project

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=2000

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Security Warning Fix
spring.jpa.open-in-view=false

# Render Deployment Port
server.port=${PORT:8080}

spring.main.allow-bean-definition-overriding=true

# Cache Disable
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.must-revalidate=true
spring.web.resources.cache.cachecontrol.no-store=true